name: open_navigation
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  latlong2: ^0.9.1
  flutter_tts: ^4.2.2
  flutter_map: ^8.0.0
  geolocator: ^13.0.2
  easy_localization: ^3.0.7+1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/navigation.jpg"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/icon/
